#!/usr/bin/env bash

# WHEREAMI

THIS_SCRIPT="$0"
while [ -h "$THIS_SCRIPT" ] ; do
  ls=`ls -ld "$THIS_SCRIPT"`
  # Drop everything prior to ->
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    THIS_SCRIPT="$link"
  else
    THIS_SCRIPT=`dirname "$THIS_SCRIPT"`/"$link"
  fi
done
SCRIPT_DIR=$(dirname "${THIS_SCRIPT}")

# Assume stepping and annotations live in the same directory as this script.
ANNO_FILE="${SCRIPT_DIR}/aspire-annotations.r"
STEP_FILE="${SCRIPT_DIR}/aspire-stepping.r"
STEPPING_ANNO_FILE="${SCRIPT_DIR}/aspire-stepping-annotations.r"

if [[ ! -e ${ANNO_FILE} ]]; then
  echo "${ANNO_FILE} not found."
  exit 1
fi

if [[ ! -e ${STEP_FILE} ]]; then
  echo "${STEP_FILE} not found."
  exit 1
fi

cat 1> ${STEPPING_ANNO_FILE} <<HED
################################################################################
# This file was generated by aspire-make-stepping.sh
# Do not modify this file by hand.
################################################################################

HED

cat ${ANNO_FILE}  >> "${STEPPING_ANNO_FILE}"

cat 1>> ${STEPPING_ANNO_FILE} <<NOTE

################################################################################
# Stepping implementation appended below
################################################################################

NOTE

cat ${STEP_FILE}  >> "${STEPPING_ANNO_FILE}"
